### ISSUE TITLE
Englische Begriffe

### ISSUE THREAD

**Issue by juliapradel** [BurdaMagazinOrg/theme-thunder-admin#21]
Basis: Channel, SEO Title und ?-Texte

„Anrisstext“ als Überschrift - ABER "Teaser Text“ über Feld, „Select image“ (bei kleinerem Screen), ?-Text

Paragraphs: „Add“, Image, Quote, Gallery, „You have unsaved changes“ (nicht im Link-Paragraphs), „Add paragraph“, am Ende: „Add different types of content with various paragraphs“ - wäre das was für einen ?-Text?

Bildbearbeitung: Media Name, Expires, ?-Text unter Media Name

Metadaten: ?-Texte unter Optionen für zeitgesteuerte Veröffentlichung, URL-Alias 

„No changes“ bei Versionen, „Compared selected revisions“, Auswahlfelder bei Vergleich

Bild(-Upload) im Media Browser: „Selct existing“, „Import image“, „Publishing status“, „Image name“, „Filter by status“, „“Filter by name“, „Apply“ „Use selected“, „Hide selected“, „Select image“, „Drop files here to upload them“, „Select entities"

Video-Browser: „Select video“, „Select existing“, „Create new video“, „Publishing status“, „Filter by status“, „Filter by name“, „Apply“, alle Felder bei „Create new video"

alle Texte bei Meta Tags

?-Text unter URL bei Link hinzufügen, Instagram und Twitter

 Content: „Apply to selected items“, „Scheduled“

Menü: Inhalt - Medien - „Add a new media"

**Comment by dbosen** [comment]
moved to drupal: https://www.drupal.org/node/2899643
