### ISSUE TITLE
Videoauswahl im Media Browser

### ISSUE THREAD

**Issue by juliapradel** [BurdaMagazinOrg/theme-thunder-admin#25]
Videos, die über den Video-Paragraph hinzugefügt werden sollen, werden im Media Browser nicht korrekt angezeigt

**Comment by dbosen** [comment]
Could you please provide steps on how to reproduce this?

**Comment by juliapradel** [comment]
I am logged in as an editor, I create a new article, I add a video paragraph, then click on "Select video" and then the browser looks like this:

![bildschirmfoto 2017-06-27 um 11 37 04](https://user-images.githubusercontent.com/22079496/27581120-02f03912-5b2d-11e7-9bd7-67536ee2e967.png)

I work with the Burda Firefox

**Comment by mtodor** [comment]
I think that something is not deployed properly or so. I have tried locally also as Editor user and FF 45 ESR - drush make and composer build. And it looks fine in both cases.
![screen shot 2017-06-29 at 13 15 31](https://user-images.githubusercontent.com/3965286/27686061-618cfb36-5cd1-11e7-90c7-ebe8d3238601.png)

**Comment by dbosen** [comment]
This was due to a old deployment at the test side.
