### ISSUE TITLE
Link paragraph layout is not so nice

### ISSUE THREAD

**Issue by mtodor** [BurdaMagazinOrg/theme-thunder-admin#36]
![screen shot 2017-06-29 at 10 40 33](https://user-images.githubusercontent.com/3965286/27679209-44f2219a-5cb8-11e7-8b21-2df99304a868.png)

Maybe we should consider to limit link paragraph to one entry -> so there is one link per paragraph and not N. Same as for Twitter, Instagram, etc.

**Comment by dbosen** [comment]
Handled in this ticket: https://www.drupal.org/node/2899369
