### ISSUE TITLE
[EB] In entity browser separation line disappears

### ISSUE THREAD

**Issue by mtodor** [BurdaMagazinOrg/theme-thunder-admin#52]
![screen shot 2017-07-11 at 13 45 53](https://user-images.githubusercontent.com/3965286/28067177-70a57666-6640-11e7-8928-c353a31d3bab.png)
For entity browser, on tab with dropzonejs -> separation line disappears.

Problem is that styles that adds separation line (border) are loaded when entity browser view is loaded and that is available only for first tab. So styles should be separated properly in distribution module and in theme.

**Comment by dbosen** [comment]
Moved to drupal.org https://www.drupal.org/node/2899611
