### ISSUE TITLE
"useless" blue line when no primary tabs on the page

### ISSUE THREAD

**Issue by pixelmord** [BurdaMagazinOrg/theme-thunder-admin#55]
I think it would look better and less confusing if that line is removed id tabs are empty
![edit_menu_main_navigation___thunder](https://user-images.githubusercontent.com/224168/28519775-2f7b39e6-706d-11e7-8ac4-c800410af2c1.png)

**Comment by dbosen** [comment]
Moved to drupal.org: https://www.drupal.org/node/2899609
