### ISSUE TITLE
Labels of multi-value fields have a low contrast

### ISSUE THREAD

**Issue by webflo** [BurdaMagazinOrg/theme-thunder-admin#59]
![low-contrast](https://user-images.githubusercontent.com/123946/28617720-ddd8975a-7201-11e7-96aa-cbf9631126b2.jpg)

**Steps to reproduce**

- Thunder default installation
- Set field cardinality of field_url (Instagram paragraph) to unlimited
- Edit the Instagram paragraph

**Comment by webflo** [comment]
Related to https://github.com/BurdaMagazinOrg/theme-thunder-admin/issues/36

**Comment by dbosen** [comment]
Also related to #44

**Comment by ol0lll** [comment]
Closing this on github and reopened it on drupal.org: https://www.drupal.org/node/2899369
