### ISSUE TITLE
Theme details element from field group module

### ISSUE THREAD

**Issue by webflo** [BurdaMagazinOrg/theme-thunder-admin#60]
The default Thunder install uses "fieldsets" to group element on the article edit page. I use the detail element because its collapsible. The details element appears in the default layout, i think it should have the same layout as fieldset (blue background etc)

**Comment by dbosen** [comment]
@webflo could you please take a look at https://github.com/BurdaMagazinOrg/theme-thunder-admin/pull/64 if that solves your problem.

**Comment by dbosen** [comment]
Moved to drupal.org: https://www.drupal.org/node/2899606
